In [14]:
from pandas import read_csv
from sklearn.metrics import cohen_kappa_score
from sklearn.metrics import matthews_corrcoef
from sklearn.metrics import roc_curve  
from sklearn.linear_model import RidgeClassifier
from sklearn import metrics
from sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import StratifiedKFold
from sklearn.metrics import classification_report
from xgboost import XGBClassifier
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn import model_selection
from sklearn.ensemble import AdaBoostClassifier 
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.svm import SVC
import matplotlib.pyplot as plt
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import ExtraTreesClassifier 
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.discriminant_analysis import QuadraticDiscriminantAnalysis
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from lightgbm import LGBMClassifier
from catboost import CatBoostClassifier
from sklearn.naive_bayes import ComplementNB
from sklearn.ensemble import BaggingClassifier
from sklearn.gaussian_process import GaussianProcessClassifier
from sklearn.gaussian_process.kernels import RBF

In [15]:
import pandas as pd
dataset= pd.read_csv("Downloads/crop.csv")
dataset.head()

label      f1      f2       f3      f4      f5      f6      f7      f8  \
0      1 -13.559 -21.407 -11.4040 -15.248 -11.923 -15.291 -2.1548 -7.8474   
1      1 -12.802 -20.335 -10.3990 -14.132 -11.096 -14.361 -2.4039 -7.5330   
2      1 -12.431 -19.902 -10.0740 -13.598 -10.829 -14.048 -2.3566 -7.4717   
3      1 -12.689 -19.529 -10.0280 -13.350 -11.056 -14.014 -2.6611 -6.8396   
4      1 -12.686 -19.278  -9.8185 -13.108 -10.932 -13.939 -2.8675 -6.5919   

        f9  ...     f165     f166    f167      f168     f169     f170  \
0 -10.0020  ...  0.18519  0.72602  5.3333  6.000000  0.29489  9.77780   
1  -9.9369  ...  0.33333 -0.48751  2.1111  0.098765  0.83333  0.33333   
2  -9.8283  ...  0.25926  0.25298  2.2222  0.172840  0.68889  0.88889   
3  -9.5006  ...  0.16049  0.43750  4.1111  0.320990  0.83333  0.33333   
4  -9.4594  ...  0.18519  0.35000  4.0000  0.444440  0.68889  0.88889   

      f171     f172     f173     f174  
0  2.44440  1.67700  0.20988  0.65422  
1  0.33333  0.84869  0.50617 -0.18898  
2  0.66667  1.27300  0.30864  0.10483  
3  0.33333  1.14910  0.38272  0.41603  
4  0.66667  1.58110  0.20988  0.50000  

[5 rows x 175 columns]

In [3]:
dataset

label        f1       f2        f3        f4        f5        f6  \
0         1 -13.55900 -21.4070 -11.40400 -15.24800 -11.92300 -15.29100   
1         1 -12.80200 -20.3350 -10.39900 -14.13200 -11.09600 -14.36100   
2         1 -12.43100 -19.9020 -10.07400 -13.59800 -10.82900 -14.04800   
3         1 -12.68900 -19.5290 -10.02800 -13.35000 -11.05600 -14.01400   
4         1 -12.68600 -19.2780  -9.81850 -13.10800 -10.93200 -13.93900   
...     ...       ...      ...       ...       ...       ...       ...   
9144      7   2.48230  -7.6870   1.07950   0.74318  -0.94070   0.90493   
9145      7   2.52340  -7.6745   1.08680   0.76189  -0.91177   0.93663   
9146      7  -1.92700 -11.4160  -2.43540  -3.45370  -4.15130  -3.48100   
9147      7   0.12483 -10.1440  -0.62193  -1.54210  -2.31000  -1.52500   
9148      7   0.20063 -10.0500  -0.59892  -1.50120  -2.25060  -1.46320   

           f7       f8       f9  ...     f165      f166    f167       f168  \
0    -2.15480  -7.8474 -10.0020  ...  0.18519  0.726020  5.3333   6.000000   
1    -2.40390  -7.5330  -9.9369  ...  0.33333 -0.487510  2.1111   0.098765   
2    -2.35660  -7.4717  -9.8283  ...  0.25926  0.252980  2.2222   0.172840   
3    -2.66110  -6.8396  -9.5006  ...  0.16049  0.437500  4.1111   0.320990   
4    -2.86750  -6.5919  -9.4594  ...  0.18519  0.350000  4.0000   0.444440   
...       ...      ...      ...  ...      ...       ...     ...        ...   
9144  1.40280 -10.1690  -8.7665  ...  0.13580  0.760800  2.3333   0.222220   
9145  1.43660 -10.1980  -8.7614  ...  0.13580 -0.383990  6.0000  10.444000   
9146  0.50845  -9.4886  -8.9802  ...  0.13580  0.754830  2.3333   0.222220   
9147  0.74676 -10.2690  -9.5218  ...  0.33333  0.059761  3.0000   0.000000   
9148  0.79955 -10.2510  -9.4514  ...  0.11111  0.168430  6.6667  11.111000   

         f169      f170     f171     f172     f173     f174  
0     0.29489   9.77780  2.44440  1.67700  0.20988  0.65422  
1     0.83333   0.33333  0.33333  0.84869  0.50617 -0.18898  
2     0.68889   0.88889  0.66667  1.27300  0.30864  0.10483  
3     0.83333   0.33333  0.33333  1.14910  0.38272  0.41603  
4     0.68889   0.88889  0.66667  1.58110  0.20988  0.50000  
...       ...       ...      ...      ...      ...      ...  
9144  0.88889   0.22222  0.22222  1.06090  0.35802  0.63246  
9145  0.12684  19.55600  4.00000  2.19720  0.11111  0.81224  
9146  0.83333   0.33333  0.33333  1.27300  0.30864  0.31623  
9147  0.94444   0.11111  0.11111  0.34883  0.80247  0.18898  
9148  0.35569  14.33300  3.00000  2.04320  0.13580  0.72732  

[9149 rows x 175 columns]

In [16]:
# Split-out validation dataset
#split the loaded dataset into two, 80% of which we will use to train, evaluate and select among our models
#20% that we will hold back as a validation dataset.
array = dataset.values
X = array[:,1:176]
y = array[:,0]
#X_train, X_test, y_train, y_test = model_selection.train_test_split(X, y, train_size=0.80,test_size=0.20, random_state=0)
X_train, X_validation, Y_train, Y_validation = train_test_split(X, y, test_size=0.20, random_state=1)

In [20]:
#K-Nearest Neighbors (KNN).
model = KNeighborsClassifier()
model.fit(X_train, Y_train)
predictions = model.predict(X_validation)
# Evaluate predictions
knn=print(accuracy_score(Y_validation, predictions))
print(confusion_matrix(Y_validation, predictions))
print(classification_report(Y_validation, predictions))
print(cohen_kappa_score(Y_validation, predictions))
print(matthews_corrcoef(Y_validation, predictions))

0.6879781420765028
[[162   0   0   5  12  17   2]
 [  0 199   0   3   0   0   1]
 [  0   1 175  18   4   1   4]
 [ 11   0  14  84  37  50  31]
 [ 26   0   0  17 131  53  33]
 [ 14   0   0  34  52 417  10]
 [ 11   0   7  31  49  23  91]]
              precision    recall  f1-score   support

         1.0       0.72      0.82      0.77       198
         2.0       0.99      0.98      0.99       203
         3.0       0.89      0.86      0.88       203
         4.0       0.44      0.37      0.40       227
         5.0       0.46      0.50      0.48       260
         6.0       0.74      0.79      0.77       527
         7.0       0.53      0.43      0.47       212

    accuracy                           0.69      1830
   macro avg       0.68      0.68      0.68      1830
weighted avg       0.68      0.69      0.68      1830

0.6233624631221919
0.6239706667948072


In [5]:
#Naive Bayes
model = GaussianNB()
model.fit(X_train, Y_train) 
predictions = model.predict(X_validation)
# Evaluate predictions
print(accuracy_score(Y_validation, predictions))
print(confusion_matrix(Y_validation, predictions))
print(classification_report(Y_validation, predictions))
print(cohen_kappa_score(Y_validation, predictions))
print(matthews_corrcoef(Y_validation, predictions))

0.8896174863387978
[[191   0   0   7   0   0   0]
 [  0 200   0   0   0   0   3]
 [  0   0 197   3   0   0   3]
 [  8   0   0 209   3   7   0]
 [  0   0   0   1 240  17   2]
 [  0   0   1   8 113 403   2]
 [ 23   0   1   0   0   0 188]]
              precision    recall  f1-score   support

         1.0       0.86      0.96      0.91       198
         2.0       1.00      0.99      0.99       203
         3.0       0.99      0.97      0.98       203
         4.0       0.92      0.92      0.92       227
         5.0       0.67      0.92      0.78       260
         6.0       0.94      0.76      0.84       527
         7.0       0.95      0.89      0.92       212

    accuracy                           0.89      1830
   macro avg       0.90      0.92      0.91      1830
weighted avg       0.91      0.89      0.89      1830

0.8685712213426172
0.8716888392769235


In [7]:
#Decision Tree
model = DecisionTreeClassifier()
model.fit(X_train, Y_train)
predictions = model.predict(X_validation)
# Evaluate predictions
print(accuracy_score(Y_validation, predictions))
print(confusion_matrix(Y_validation, predictions))
print(classification_report(Y_validation, predictions))
print(cohen_kappa_score(Y_validation, predictions))
print(matthews_corrcoef(Y_validation, predictions))

0.9907103825136612
[[198   0   0   0   0   0   0]
 [  0 203   0   0   0   0   0]
 [  1   0 198   2   2   0   0]
 [  0   0   0 224   1   2   0]
 [  0   0   0   0 257   3   0]
 [  0   0   0   3   1 523   0]
 [  0   1   0   0   0   1 210]]
              precision    recall  f1-score   support

         1.0       0.99      1.00      1.00       198
         2.0       1.00      1.00      1.00       203
         3.0       1.00      0.98      0.99       203
         4.0       0.98      0.99      0.98       227
         5.0       0.98      0.99      0.99       260
         6.0       0.99      0.99      0.99       527
         7.0       1.00      0.99      1.00       212

    accuracy                           0.99      1830
   macro avg       0.99      0.99      0.99      1830
weighted avg       0.99      0.99      0.99      1830

0.9888284245672675
0.9888355622311826


In [8]:
#Adaboost
model = AdaBoostClassifier(DecisionTreeClassifier(max_depth=1),n_estimators=200)
model.fit(X_train, Y_train)
predictions = model.predict(X_validation)
# Evaluate predictions
print(accuracy_score(Y_validation, predictions))
print(confusion_matrix(Y_validation, predictions))
print(classification_report(Y_validation, predictions))
print(cohen_kappa_score(Y_validation, predictions))
print(matthews_corrcoef(Y_validation, predictions))

0.6355191256830601
[[  0   0   0   0 195   0   3]
 [  0 193   0   0   0   0  10]
 [  0   0   0   0 201   0   2]
 [  0   0   0   0 214  13   0]
 [  0   0   0   0 256   4   0]
 [  0   0   0   0  23 504   0]
 [  0   0   0   0   2   0 210]]
              precision    recall  f1-score   support

         1.0       0.00      0.00      0.00       198
         2.0       1.00      0.95      0.97       203
         3.0       0.00      0.00      0.00       203
         4.0       0.00      0.00      0.00       227
         5.0       0.29      0.98      0.44       260
         6.0       0.97      0.96      0.96       527
         7.0       0.93      0.99      0.96       212

    accuracy                           0.64      1830
   macro avg       0.46      0.55      0.48      1830
weighted avg       0.54      0.64      0.56      1830

0.5570750208469863
0.6207601486886777


/home/ps/.local/lib/python3.6/site-packages/sklearn/metrics/_classification.py:1221: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [9]:
#Support Vector Machine
model = SVC(gamma='auto')
model.fit(X_train, Y_train)
predictions = model.predict(X_validation)
# Evaluate predictions
print(accuracy_score(Y_validation, predictions))
print(confusion_matrix(Y_validation, predictions))
print(classification_report(Y_validation, predictions))
print(cohen_kappa_score(Y_validation, predictions))
print(matthews_corrcoef(Y_validation, predictions))

0.28797814207650274
[[  0   0   0   0   0 198   0]
 [  0   0   0   0   0 203   0]
 [  0   0   0   0   0 203   0]
 [  0   0   0   0   0 227   0]
 [  0   0   0   0   0 260   0]
 [  0   0   0   0   0 527   0]
 [  0   0   0   0   0 212   0]]
              precision    recall  f1-score   support

         1.0       0.00      0.00      0.00       198
         2.0       0.00      0.00      0.00       203
         3.0       0.00      0.00      0.00       203
         4.0       0.00      0.00      0.00       227
         5.0       0.00      0.00      0.00       260
         6.0       0.29      1.00      0.45       527
         7.0       0.00      0.00      0.00       212

    accuracy                           0.29      1830
   macro avg       0.04      0.14      0.06      1830
weighted avg       0.08      0.29      0.13      1830

0.0
0.0


/home/ps/.local/lib/python3.6/site-packages/sklearn/metrics/_classification.py:1221: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/ps/.local/lib/python3.6/site-packages/sklearn/metrics/_classification.py:846: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)


In [21]:
from sklearn.ensemble import RandomForestClassifier
model = RandomForestClassifier(n_estimators=100)
model.fit(X_train, Y_train)
predictions = model.predict(X_validation)
# Evaluate predictions
rfc=print(accuracy_score(Y_validation, predictions))
print(confusion_matrix(Y_validation, predictions))
print(classification_report(Y_validation, predictions))
print(cohen_kappa_score(Y_validation, predictions))
print(matthews_corrcoef(Y_validation, predictions))

0.9972677595628415
[[198   0   0   0   0   0   0]
 [  0 203   0   0   0   0   0]
 [  0   0 201   2   0   0   0]
 [  0   0   0 227   0   0   0]
 [  0   0   0   1 257   2   0]
 [  0   0   0   0   0 527   0]
 [  0   0   0   0   0   0 212]]
              precision    recall  f1-score   support

         1.0       1.00      1.00      1.00       198
         2.0       1.00      1.00      1.00       203
         3.0       1.00      0.99      1.00       203
         4.0       0.99      1.00      0.99       227
         5.0       1.00      0.99      0.99       260
         6.0       1.00      1.00      1.00       527
         7.0       1.00      1.00      1.00       212

    accuracy                           1.00      1830
   macro avg       1.00      1.00      1.00      1830
weighted avg       1.00      1.00      1.00      1830

0.9967144560701232
0.9967191290360112


In [18]:
gb_clf = GradientBoostingClassifier(n_estimators=50, learning_rate=1, max_features=2, max_depth=2, random_state=0)
gb_clf.fit(X_train, Y_train)
predictions = model.predict(X_validation)
# Evaluate predictions
print(accuracy_score(Y_validation, predictions))
print(confusion_matrix(Y_validation, predictions))
print(classification_report(Y_validation, predictions))
print(cohen_kappa_score(Y_validation, predictions))
print(matthews_corrcoef(Y_validation, predictions))

0.9972677595628415
[[198   0   0   0   0   0   0]
 [  0 203   0   0   0   0   0]
 [  0   0 201   2   0   0   0]
 [  0   0   0 227   0   0   0]
 [  0   0   0   1 258   1   0]
 [  0   0   0   0   0 526   1]
 [  0   0   0   0   0   0 212]]
              precision    recall  f1-score   support

         1.0       1.00      1.00      1.00       198
         2.0       1.00      1.00      1.00       203
         3.0       1.00      0.99      1.00       203
         4.0       0.99      1.00      0.99       227
         5.0       1.00      0.99      1.00       260
         6.0       1.00      1.00      1.00       527
         7.0       1.00      1.00      1.00       212

    accuracy                           1.00      1830
   macro avg       1.00      1.00      1.00      1830
weighted avg       1.00      1.00      1.00      1830

0.9967151425466584
0.9967183629879925


In [19]:
model = ExtraTreesClassifier(n_estimators = 3, criterion ='entropy', max_features = 174) 
model.fit(X_train, Y_train)
predictions = model.predict(X_validation)
# Evaluate predictions
print(accuracy_score(Y_validation, predictions))
print(confusion_matrix(Y_validation, predictions))
print(classification_report(Y_validation, predictions))
print(cohen_kappa_score(Y_validation, predictions))
print(matthews_corrcoef(Y_validation, predictions))

0.9956284153005465
[[198   0   0   0   0   0   0]
 [  0 203   0   0   0   0   0]
 [  0   0 201   2   0   0   0]
 [  0   0   0 226   0   1   0]
 [  0   0   0   0 257   3   0]
 [  0   0   0   0   0 526   1]
 [  0   1   0   0   0   0 211]]
              precision    recall  f1-score   support

         1.0       1.00      1.00      1.00       198
         2.0       1.00      1.00      1.00       203
         3.0       1.00      0.99      1.00       203
         4.0       0.99      1.00      0.99       227
         5.0       1.00      0.99      0.99       260
         6.0       0.99      1.00      1.00       527
         7.0       1.00      1.00      1.00       212

    accuracy                           1.00      1830
   macro avg       1.00      1.00      1.00      1830
weighted avg       1.00      1.00      1.00      1830

0.9947426086787895
0.9947469403146766


In [13]:
model = QuadraticDiscriminantAnalysis()
model.fit(X_train, Y_train)
predictions = model.predict(X_validation)
# Evaluate predictions
print(accuracy_score(Y_validation, predictions))
print(confusion_matrix(Y_validation, predictions))
print(classification_report(Y_validation, predictions))
print(cohen_kappa_score(Y_validation, predictions))
print(matthews_corrcoef(Y_validation, predictions))

/home/ps/.local/lib/python3.6/site-packages/sklearn/discriminant_analysis.py:715: UserWarning: Variables are collinear
  warnings.warn("Variables are collinear")


0.8398907103825136
[[198   0   0   0   0   0   0]
 [  0 202   0   0   0   0   1]
 [  0   0 161   0   0   0  42]
 [  0   0   0 184   0  18  25]
 [  0   0   0   0  82 108  70]
 [  0   0   0   1   0 498  28]
 [  0   0   0   0   0   0 212]]
              precision    recall  f1-score   support

         1.0       1.00      1.00      1.00       198
         2.0       1.00      1.00      1.00       203
         3.0       1.00      0.79      0.88       203
         4.0       0.99      0.81      0.89       227
         5.0       1.00      0.32      0.48       260
         6.0       0.80      0.94      0.87       527
         7.0       0.56      1.00      0.72       212

    accuracy                           0.84      1830
   macro avg       0.91      0.84      0.83      1830
weighted avg       0.89      0.84      0.83      1830

0.8059889105506081
0.8168366924126478


In [14]:
model = LinearDiscriminantAnalysis()
model.fit(X_train, Y_train)
predictions = model.predict(X_validation)
# Evaluate predictions
print(accuracy_score(Y_validation, predictions))
print(confusion_matrix(Y_validation, predictions))
print(classification_report(Y_validation, predictions))
print(cohen_kappa_score(Y_validation, predictions))
print(matthews_corrcoef(Y_validation, predictions))

0.9961748633879781
[[198   0   0   0   0   0   0]
 [  0 203   0   0   0   0   0]
 [  0   0 201   2   0   0   0]
 [  0   0   0 227   0   0   0]
 [  0   0   0   0 258   2   0]
 [  0   0   0   0   0 525   2]
 [  0   0   1   0   0   0 211]]
              precision    recall  f1-score   support

         1.0       1.00      1.00      1.00       198
         2.0       1.00      1.00      1.00       203
         3.0       1.00      0.99      0.99       203
         4.0       0.99      1.00      1.00       227
         5.0       1.00      0.99      1.00       260
         6.0       1.00      1.00      1.00       527
         7.0       0.99      1.00      0.99       212

    accuracy                           1.00      1830
   macro avg       1.00      1.00      1.00      1830
weighted avg       1.00      1.00      1.00      1830

0.9954012391883349
0.9954030260988705


In [15]:
model = LGBMClassifier()
model.fit(X_train, Y_train)
predictions = model.predict(X_validation)
# Evaluate predictions
print(accuracy_score(Y_validation, predictions))
print(confusion_matrix(Y_validation, predictions))
print(classification_report(Y_validation, predictions))
print(cohen_kappa_score(Y_validation, predictions))
print(matthews_corrcoef(Y_validation, predictions))

0.9972677595628415
[[198   0   0   0   0   0   0]
 [  0 203   0   0   0   0   0]
 [  0   0 200   3   0   0   0]
 [  0   0   0 227   0   0   0]
 [  0   0   0   1 259   0   0]
 [  0   0   0   0   0 526   1]
 [  0   0   0   0   0   0 212]]
              precision    recall  f1-score   support

         1.0       1.00      1.00      1.00       198
         2.0       1.00      1.00      1.00       203
         3.0       1.00      0.99      0.99       203
         4.0       0.98      1.00      0.99       227
         5.0       1.00      1.00      1.00       260
         6.0       1.00      1.00      1.00       527
         7.0       1.00      1.00      1.00       212

    accuracy                           1.00      1830
   macro avg       1.00      1.00      1.00      1830
weighted avg       1.00      1.00      1.00      1830

0.9967154290834216
0.9967204425829733


In [16]:
model = CatBoostClassifier(iterations=2,learning_rate=1,depth=2)
model.fit(X_train, Y_train)
predictions = model.predict(X_validation)
# Evaluate predictions
print(accuracy_score(Y_validation, predictions))
print(confusion_matrix(Y_validation, predictions))
print(classification_report(Y_validation, predictions))
print(cohen_kappa_score(Y_validation, predictions))
print(matthews_corrcoef(Y_validation, predictions))

0:	learn: 1.0976612	total: 111ms	remaining: 111ms
1:	learn: 0.5758809	total: 130ms	remaining: 0us
0.7912568306010929
[[178   0   0  10   0   0  10]
 [  0 203   0   0   0   0   0]
 [  0  10 184   9   0   0   0]
 [  0   0   9 206   0   9   3]
 [ 21   0   0 238   0   1   0]
 [  1   0   1  38   0 485   2]
 [  2  18   0   0   0   0 192]]
              precision    recall  f1-score   support

         1.0       0.88      0.90      0.89       198
         2.0       0.88      1.00      0.94       203
         3.0       0.95      0.91      0.93       203
         4.0       0.41      0.91      0.57       227
         5.0       0.00      0.00      0.00       260
         6.0       0.98      0.92      0.95       527
         7.0       0.93      0.91      0.92       212

    accuracy                           0.79      1830
   macro avg       0.72      0.79      0.74      1830
weighted avg       0.74      0.79      0.75      1830

0.7507054714917482
0.7707226601008871


/home/ps/.local/lib/python3.6/site-packages/sklearn/metrics/_classification.py:1221: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [17]:
model = RidgeClassifier()
model.fit(X_train, Y_train)
predictions = model.predict(X_validation)
# Evaluate predictions
print(accuracy_score(Y_validation, predictions))
print(confusion_matrix(Y_validation, predictions))
print(classification_report(Y_validation, predictions))
print(cohen_kappa_score(Y_validation, predictions))
print(matthews_corrcoef(Y_validation, predictions))

0.992896174863388
[[198   0   0   0   0   0   0]
 [  0 203   0   0   0   0   0]
 [  0   0 201   1   1   0   0]
 [  5   0   0 222   0   0   0]
 [  0   0   0   0 258   1   1]
 [  0   0   0   0   0 525   2]
 [  1   0   1   0   0   0 210]]
              precision    recall  f1-score   support

         1.0       0.97      1.00      0.99       198
         2.0       1.00      1.00      1.00       203
         3.0       1.00      0.99      0.99       203
         4.0       1.00      0.98      0.99       227
         5.0       1.00      0.99      0.99       260
         6.0       1.00      1.00      1.00       527
         7.0       0.99      0.99      0.99       212

    accuracy                           0.99      1830
   macro avg       0.99      0.99      0.99      1830
weighted avg       0.99      0.99      0.99      1830

0.9914607961165467
0.9914707748489294


In [13]:
model= LogisticRegression(max_iter=2000,random_state = 0)
model.fit(X_train,Y_train)
predictions = model.predict(X_validation)
# Evaluate predictions
print(accuracy_score(Y_validation, predictions))
print(confusion_matrix(Y_validation, predictions))
print(classification_report(Y_validation, predictions))
print(cohen_kappa_score(Y_validation, predictions))
print(matthews_corrcoef(Y_validation, predictions))

0.7284153005464481
[[185   0   0   0   0  12   1]
 [  0 195   3   4   0   1   0]
 [  0   0 194   5   1   3   0]
 [ 10  12   0  80  27  80  18]
 [  6   0   0   3 114  91  46]
 [  8   0   5   5  25 465  19]
 [  9   0   4  25  15  59 100]]
              precision    recall  f1-score   support

         1.0       0.85      0.93      0.89       198
         2.0       0.94      0.96      0.95       203
         3.0       0.94      0.96      0.95       203
         4.0       0.66      0.35      0.46       227
         5.0       0.63      0.44      0.52       260
         6.0       0.65      0.88      0.75       527
         7.0       0.54      0.47      0.51       212

    accuracy                           0.73      1830
   macro avg       0.74      0.71      0.72      1830
weighted avg       0.72      0.73      0.71      1830

0.6672335281492826
0.6739459362225759


/home/ps/.local/lib/python3.6/site-packages/sklearn/linear_model/_logistic.py:764: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


In [19]:
model = XGBClassifier()
model.fit(X_train, Y_train)
predictions = model.predict(X_validation)
# Evaluate predictions
print(accuracy_score(Y_validation, predictions))
print(confusion_matrix(Y_validation, predictions))
print(classification_report(Y_validation, predictions)) 
print(cohen_kappa_score(Y_validation, predictions))
print(matthews_corrcoef(Y_validation, predictions))

0.9972677595628415
[[198   0   0   0   0   0   0]
 [  0 203   0   0   0   0   0]
 [  0   0 199   4   0   0   0]
 [  0   0   0 227   0   0   0]
 [  0   0   0   0 260   0   0]
 [  0   0   0   0   0 526   1]
 [  0   0   0   0   0   0 212]]
              precision    recall  f1-score   support

         1.0       1.00      1.00      1.00       198
         2.0       1.00      1.00      1.00       203
         3.0       1.00      0.98      0.99       203
         4.0       0.98      1.00      0.99       227
         5.0       1.00      1.00      1.00       260
         6.0       1.00      1.00      1.00       527
         7.0       1.00      1.00      1.00       212

    accuracy                           1.00      1830
   macro avg       1.00      1.00      1.00      1830
weighted avg       1.00      1.00      1.00      1830

0.9967153618755822
0.9967214470947032


In [20]:
seed = 8
num_trees = 500
base_cls = DecisionTreeClassifier()
model = BaggingClassifier(base_estimator = base_cls, n_estimators = num_trees, random_state = seed)
model.fit(X_train, Y_train)
predictions = model.predict(X_validation)
# Evaluate predictions
print(accuracy_score(Y_validation, predictions))
print(confusion_matrix(Y_validation, predictions))
print(classification_report(Y_validation, predictions)) 
print(cohen_kappa_score(Y_validation, predictions))
print(matthews_corrcoef(Y_validation, predictions))

0.9978142076502732
[[198   0   0   0   0   0   0]
 [  0 203   0   0   0   0   0]
 [  0   0 202   1   0   0   0]
 [  0   0   0 226   0   1   0]
 [  0   0   0   0 259   1   0]
 [  0   0   0   1   0 526   0]
 [  0   0   0   0   0   0 212]]
              precision    recall  f1-score   support

         1.0       1.00      1.00      1.00       198
         2.0       1.00      1.00      1.00       203
         3.0       1.00      1.00      1.00       203
         4.0       0.99      1.00      0.99       227
         5.0       1.00      1.00      1.00       260
         6.0       1.00      1.00      1.00       527
         7.0       1.00      1.00      1.00       212

    accuracy                           1.00      1830
   macro avg       1.00      1.00      1.00      1830
weighted avg       1.00      1.00      1.00      1830

0.9973718083358916
0.9973725300532282


In [21]:
model = BaggingClassifier(base_estimator=SVC(),n_estimators=10, random_state=0)
model.fit(X_train, Y_train)
predictions = model.predict(X_validation)
# Evaluate predictions
print(accuracy_score(Y_validation, predictions))
print(confusion_matrix(Y_validation, predictions))
print(classification_report(Y_validation, predictions)) 
print(cohen_kappa_score(Y_validation, predictions))
print(matthews_corrcoef(Y_validation, predictions))

0.6770491803278689
[[142   0   0   0  19  36   1]
 [  0 195   5   1   0   0   2]
 [  0   0 161  27   0   3  12]
 [  7   4   8  44  38  68  58]
 [ 20   0   0   0 119  80  41]
 [  4   0   0   0  52 460  11]
 [  4   0   2   0  55  33 118]]
              precision    recall  f1-score   support

         1.0       0.80      0.72      0.76       198
         2.0       0.98      0.96      0.97       203
         3.0       0.91      0.79      0.85       203
         4.0       0.61      0.19      0.29       227
         5.0       0.42      0.46      0.44       260
         6.0       0.68      0.87      0.76       527
         7.0       0.49      0.56      0.52       212

    accuracy                           0.68      1830
   macro avg       0.70      0.65      0.66      1830
weighted avg       0.68      0.68      0.66      1830

0.6049824520650462
0.6107885881232517


In [22]:
model = SVC(kernel = 'rbf', random_state = 0) 
model.fit(X_train, Y_train)
predictions = model.predict(X_validation)
# Evaluate predictions
print(accuracy_score(Y_validation, predictions))
print(confusion_matrix(Y_validation, predictions))
print(classification_report(Y_validation, predictions)) 
print(cohen_kappa_score(Y_validation, predictions))
print(matthews_corrcoef(Y_validation, predictions))

0.6743169398907104
[[144   0   0   0  16  37   1]
 [  0 195   4   1   0   0   3]
 [  0   0 159  27   0   3  14]
 [  7   4   8  44  37  69  58]
 [ 22   0   0   0 115  80  43]
 [  4   0   0   0  50 462  11]
 [  4   0   2   0  57  34 115]]
              precision    recall  f1-score   support

         1.0       0.80      0.73      0.76       198
         2.0       0.98      0.96      0.97       203
         3.0       0.92      0.78      0.85       203
         4.0       0.61      0.19      0.29       227
         5.0       0.42      0.44      0.43       260
         6.0       0.67      0.88      0.76       527
         7.0       0.47      0.54      0.50       212

    accuracy                           0.67      1830
   macro avg       0.70      0.65      0.65      1830
weighted avg       0.68      0.67      0.66      1830

0.6014713711470505
0.6074143793120087


In [23]:
model = BaggingClassifier(base_estimator=KNeighborsClassifier(),n_estimators=10, random_state=0)
model.fit(X_train, Y_train)
predictions = model.predict(X_validation)
# Evaluate predictions
print(accuracy_score(Y_validation, predictions))
print(confusion_matrix(Y_validation, predictions))
print(classification_report(Y_validation, predictions)) 
print(cohen_kappa_score(Y_validation, predictions))
print(matthews_corrcoef(Y_validation, predictions))

0.6879781420765028
[[155   0   0   4  19  19   1]
 [  0 199   0   3   0   0   1]
 [  0   0 177  17   2   1   6]
 [ 10   0  15  74  33  60  35]
 [ 21   0   0   9 123  66  41]
 [ 10   0   0  25  57 420  15]
 [  9   0   5  22  38  27 111]]
              precision    recall  f1-score   support

         1.0       0.76      0.78      0.77       198
         2.0       1.00      0.98      0.99       203
         3.0       0.90      0.87      0.89       203
         4.0       0.48      0.33      0.39       227
         5.0       0.45      0.47      0.46       260
         6.0       0.71      0.80      0.75       527
         7.0       0.53      0.52      0.53       212

    accuracy                           0.69      1830
   macro avg       0.69      0.68      0.68      1830
weighted avg       0.68      0.69      0.68      1830

0.6221159093350133
0.6232614296259951


In [ ]:
model = GaussianProcessClassifier()
model.fit(X_train, Y_train)
predictions = model.predict(X_validation)
# Evaluate predictions
print(accuracy_score(Y_validation, predictions))
print(confusion_matrix(Y_validation, predictions))
print(classification_report(Y_validation, predictions)) 
print(cohen_kappa_score(Y_validation, predictions))
print(matthews_corrcoef(Y_validation, predictions))